config/routes.rb
Rails.application.routes.draw do
  resources :categories
  
  root "events#index"
  
  get "event/filter/:filter" => "events#index", as: :filtered_events

  resources :events do
    resources :registrations
    resources :likes
  end
  
  resource :session, only: [:new, :create, :destroy]

  resources :users
  get "signup" => "users#new"

end

app/views/layouts/_flash.html.erb
<% if flash[:notice] %>
<div class="flash notice">
    <%= flash[:notice] %>
</div>
<% end %>

<% if flash[:alert] %>
<div class="flash alert">
    <%= flash[:alert] %>
</div>
<% end %>

app/views/layouts/_footer.html.erb
<footer>
    <p>
        &copy; <%= Time.now.year %>
        <%= link_to 'Dave Divinagracia', 'https://github.com/idvd20' %>        
    </p>
</footer>

app/views/layouts/_header.html.erb
<header>
    <nav>
    <%= link_to image_tag('logo.png'), root_path %>
    <ul class="left">
        <li>
            <%= link_to 'Upcoming', events_path %>
        </li>
        <li>
            <%= link_to 'Past', filtered_events_path(:past) %>
        </li>
        <li>
            <%= link_to 'Free', filtered_events_path(:free) %>
        </li>
        <li>
            <%= link_to 'Recent', filtered_events_path(:recent) %>
        </li>
    </ul>
    <ul class="right">
        <% if current_user %>
            <li>
                <%= link_to current_user.name, current_user %>
            </li>
            <li>
                <%= link_to 'Sign Out', session_path, 
                    data: { turbo_method: :delete}, 
                    class: "button" %>
            </li>
        <% else %>
            <li>
                <%= link_to 'Sign in', new_session_path, class: "button" %>
            </li>        
            <li>
                <%= link_to 'Sign up', signup_path, class: "button" %>
            </li>
        <% end %>
    </ul>
    </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Eventz</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'layouts/header' %>

    <div class="content">
      <%= render 'layouts/flash' %>
      <%= yield %>
    </div>

    <%= render 'layouts/footer' %>
  </body>
</html>